name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.12
      with:
        hugo-version: '0.74.3'
        # extended: true

    - name: Copy template files
      run: cp -r ./repositories/hugo-theme-docdock/* ./src/themes/docdock

    - name: Copy customized template files
      run: cp -r ./src/themes/docdock.customize/* ./src/themes/docdock
      
    - name: Remove previous output
      run: rm -r ./docs

    - name: Run Hugo
      run: (cd ./src && hugo --minify)

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatically generate site" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
